### ISSUE TITLE
Reminder: Add <parallelScheme>SCENARIO</parallelScheme> to run scenarios in parallel

### ISSUE THREAD

**Issue by KevinMarkVI** [saucelabs-sample-test-frameworks/Java-CucumberJVM-JUnit#9]
<plugin>
                <groupId>com.github.temyers</groupId>
                <artifactId>cucumber-jvm-parallel-plugin</artifactId>
                <version>${cucumber.jvm.parallel.version}</version>
                <executions>
                    <execution>
                        <id>generateRunners</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>generateRunners</goal>
                        </goals>
                        <configuration>
                            
                            
                            <glue>com.yourcompany.step.definitions</glue>
                            
                            
                            <outputDirectory>${project.build.directory}/generated-test-sources/features</outputDirectory>
                            
                            <featuresDirectory>src/test/resources/features/</featuresDirectory>
                            
                            <cucumberOutputDir>${project.build.directory}/cucumber_reports/${suitename}_results</cucumberOutputDir>
                            
                            <format>junit</format>
                            
                            <strict>true</strict>
                            
                            <monochrome>true</monochrome>
                            
                            <tags>"~@ignore"</tags>

                            <namingScheme>pattern</namingScheme>
                            
                            <namingPattern>{f}_Parallel{c}IT</namingPattern>
                            
                            <parallelScheme>SCENARIO</parallelScheme>
                            
                            
                            <filterFeaturesByTags>true</filterFeaturesByTags>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

**Comment by mmerrell-sauce** [comment]
We've pivoted to using the surefire plugin for parallelization, rather than cucumber-jvm-parallel
